//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 02:01:38 AM IST 
//


package com.bestbuy.searchplatform.integrationtests.model;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="boostsAndBlock">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="categoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="searchTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="boostBlockId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="boostProduct">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="skuId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="blockProduct">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="skuId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="searchProfileId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "boostsAndBlock"
})
@XmlRootElement(name = "boostsAndBlocks")
public class BoostsAndBlocks {

    @XmlElement(required = true)
    protected List<BoostsAndBlocks.BoostsAndBlock> boostsAndBlock;

    /**
     * Gets the value of the boostsAndBlock property.
     * 
     * @return
     *     possible object is
     *     {@link BoostsAndBlocks.BoostsAndBlock }
     *     
     */
    public List<BoostsAndBlocks.BoostsAndBlock> getBoostsAndBlock() {
        return boostsAndBlock;
    }

    /**
     * Sets the value of the boostsAndBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoostsAndBlocks.BoostsAndBlock }
     *     
     */
    public void setBoostsAndBlock(List<BoostsAndBlocks.BoostsAndBlock> value) {
        this.boostsAndBlock = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="categoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="searchTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="boostBlockId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="boostProduct">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="skuId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="blockProduct">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="skuId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="searchProfileId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "categoryId",
        "categoryPath",
        "searchTerm",
        "boostBlockId",
        "boostProduct",
        "blockProduct",
        "searchProfileId"
    })
    public static class BoostsAndBlock {

        @XmlElement(required = true)
        protected String categoryId;
        @XmlElement(required = true)
        protected String categoryPath;
        @XmlElement(required = true)
        protected String searchTerm;
        @XmlElement(required = true)
        protected String boostBlockId;
        @XmlElement(required = true)
        protected List<BoostsAndBlocks.BoostsAndBlock.BoostProduct> boostProduct;
        @XmlElement(required = true)
        protected List<BoostsAndBlocks.BoostsAndBlock.BlockProduct> blockProduct;
        protected long searchProfileId;

        /**
         * Gets the value of the categoryId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryId() {
            return categoryId;
        }

        /**
         * Sets the value of the categoryId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryId(String value) {
            this.categoryId = value;
        }

        /**
         * Gets the value of the categoryPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryPath() {
            return categoryPath;
        }

        /**
         * Sets the value of the categoryPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryPath(String value) {
            this.categoryPath = value;
        }

        /**
         * Gets the value of the searchTerm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchTerm() {
            return searchTerm;
        }

        /**
         * Sets the value of the searchTerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchTerm(String value) {
            this.searchTerm = value;
        }

        /**
         * Gets the value of the boostBlockId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBoostBlockId() {
            return boostBlockId;
        }

        /**
         * Sets the value of the boostBlockId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBoostBlockId(String value) {
            this.boostBlockId = value;
        }

        /**
         * Gets the value of the boostProduct property.
         * 
         * @return
         *     possible object is
         *     {@link BoostsAndBlocks.BoostsAndBlock.BoostProduct }
         *     
         */
        public List<BoostsAndBlocks.BoostsAndBlock.BoostProduct> getBoostProduct() {
            return boostProduct;
        }

        /**
         * Sets the value of the boostProduct property.
         * 
         * @param value
         *     allowed object is
         *     {@link BoostsAndBlocks.BoostsAndBlock.BoostProduct }
         *     
         */
        public void setBoostProduct(List<BoostsAndBlocks.BoostsAndBlock.BoostProduct> value) {
            this.boostProduct = value;
        }

        /**
         * Gets the value of the blockProduct property.
         * 
         * @return
         *     possible object is
         *     {@link BoostsAndBlocks.BoostsAndBlock.BlockProduct }
         *     
         */
        public List<BoostsAndBlocks.BoostsAndBlock.BlockProduct> getBlockProduct() {
            return blockProduct;
        }

        /**
         * Sets the value of the blockProduct property.
         * 
         * @param value
         *     allowed object is
         *     {@link BoostsAndBlocks.BoostsAndBlock.BlockProduct }
         *     
         */
        public void setBlockProduct(List<BoostsAndBlocks.BoostsAndBlock.BlockProduct> value) {
            this.blockProduct = value;
        }

        /**
         * Gets the value of the searchProfileId property.
         * 
         */
        public long getSearchProfileId() {
            return searchProfileId;
        }

        /**
         * Sets the value of the searchProfileId property.
         * 
         */
        public void setSearchProfileId(long value) {
            this.searchProfileId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="skuId" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "productName",
            "skuId",
            "position"
        })
        public static class BlockProduct {

            @XmlElement(required = true)
            protected String productName;
            protected String skuId;
            protected long position;

            /**
             * Gets the value of the productName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductName() {
                return productName;
            }

            /**
             * Sets the value of the productName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductName(String value) {
                this.productName = value;
            }

            /**
             * Gets the value of the skuId property.
             * 
             */
            public String getSkuId() {
                return skuId;
            }

            /**
             * Sets the value of the skuId property.
             * 
             */
            public void setSkuId(String value) {
                this.skuId = value;
            }

            /**
             * Gets the value of the position property.
             * 
             */
            public long getPosition() {
                return position;
            }

            /**
             * Sets the value of the position property.
             * 
             */
            public void setPosition(long value) {
                this.position = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="skuId" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "productName",
            "skuId",
            "position"
        })
        public static class BoostProduct {

            @XmlElement(required = true)
            protected String productName;
            protected String skuId;
            protected long position;

            /**
             * Gets the value of the productName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductName() {
                return productName;
            }

            /**
             * Sets the value of the productName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductName(String value) {
                this.productName = value;
            }

            /**
             * Gets the value of the skuId property.
             * 
             */
            public String getSkuId() {
                return skuId;
            }

            /**
             * Sets the value of the skuId property.
             * 
             */
            public void setSkuId(String value) {
                this.skuId = value;
            }

            /**
             * Gets the value of the position property.
             * 
             */
            public long getPosition() {
                return position;
            }

            /**
             * Sets the value of the position property.
             * 
             */
            public void setPosition(long value) {
                this.position = value;
            }

        }

    }

}
