//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 09:43:28 PM IST 
//


package com.bestbuy.searchplatform.integrationtests.model;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="facet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="excludeList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="attributeValueId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="attributeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="attrValuedisplay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="promoteList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="attributeValueId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="attributeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="attrValuedisplay" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="systemName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="facetId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="sortType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="minValue" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="maxValue" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="facetDisplay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="attributeId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="displayMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="glossaryItem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="displayFacetRemoveLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="displayMobileFacet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="displayMobileFacetRemoveLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="displayRecurrence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="categoryWrapper">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="applySubCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="displayDepFacet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="displayContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="categoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "facet"
})
@XmlRootElement(name = "facets")
public class Facets {

    @XmlElement(required = true)
    protected List<Facets.Facet> facet;

    /**
     * Gets the value of the facet property.
     * 
     * @return
     *     possible object is
     *     {@link Facets.Facet }
     *     
     */
    public List<Facets.Facet> getFacet() {
        return facet;
    }

    /**
     * Sets the value of the facet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Facets.Facet }
     *     
     */
    public void setFacet(List<Facets.Facet> value) {
        this.facet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="excludeList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="attributeValueId" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="attributeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="attrValuedisplay" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="promoteList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="attributeValueId" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="attributeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="attrValuedisplay" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="systemName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="facetId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="sortType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="minValue" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="maxValue" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="facetDisplay" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="attributeId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="displayMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="glossaryItem" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="displayFacetRemoveLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="displayMobileFacet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="displayMobileFacetRemoveLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="displayRecurrence" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="categoryWrapper">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="applySubCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="displayDepFacet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="displayContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="categoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "excludeList",
        "promoteList",
        "systemName",
        "displayName",
        "facetId",
        "sortType",
        "minValue",
        "maxValue",
        "facetDisplay",
        "attributeId",
        "attributeName",
        "startDate",
        "endDate",
        "displayMode",
        "glossaryItem",
        "displayFacetRemoveLink",
        "displayMobileFacet",
        "displayMobileFacetRemoveLink",
        "displayRecurrence",
        "categoryWrapper"
    })
    public static class Facet {

        @XmlElement(required = true)
        protected List<Facets.Facet.ExcludeList> excludeList;
        @XmlElement(required = true)
        protected List<Facets.Facet.PromoteList> promoteList;
        @XmlElement(required = true)
        protected String systemName;
        @XmlElement(required = true)
        protected String displayName;
        protected String facetId;
        @XmlElement(required = true)
        protected String sortType;
        protected long minValue;
        protected long maxValue;
        @XmlElement(required = true)
        protected String facetDisplay;
        protected String attributeId;
        @XmlElement(required = true)
        protected String attributeName;
        @XmlElement(required = true)
        protected String startDate;
        @XmlElement(required = true)
        protected String endDate;
        @XmlElement(required = true)
        protected String displayMode;
        @XmlElement(required = true)
        protected String glossaryItem;
        @XmlElement(required = true)
        protected String displayFacetRemoveLink;
        @XmlElement(required = true)
        protected String displayMobileFacet;
        @XmlElement(required = true)
        protected String displayMobileFacetRemoveLink;
        @XmlElement(required = true)
        protected String displayRecurrence;
        @XmlElement(required = true)
        protected List<Facets.Facet.CategoryWrapper> categoryWrapper;

        /**
         * Gets the value of the excludeList property.
         * 
         * @return
         *     possible object is
         *     {@link Facets.Facet.ExcludeList }
         *     
         */
        public List<Facets.Facet.ExcludeList> getExcludeList() {
            return excludeList;
        }

        /**
         * Sets the value of the excludeList property.
         * 
         * @param value
         *     allowed object is
         *     {@link Facets.Facet.ExcludeList }
         *     
         */
        public void setExcludeList(List<Facets.Facet.ExcludeList> value) {
            this.excludeList = value;
        }

        /**
         * Gets the value of the promoteList property.
         * 
         * @return
         *     possible object is
         *     {@link Facets.Facet.PromoteList }
         *     
         */
        public List<Facets.Facet.PromoteList> getPromoteList() {
            return promoteList;
        }

        /**
         * Sets the value of the promoteList property.
         * 
         * @param value
         *     allowed object is
         *     {@link Facets.Facet.PromoteList }
         *     
         */
        public void setPromoteList(List<Facets.Facet.PromoteList> value) {
            this.promoteList = value;
        }

        /**
         * Gets the value of the systemName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystemName() {
            return systemName;
        }

        /**
         * Sets the value of the systemName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystemName(String value) {
            this.systemName = value;
        }

        /**
         * Gets the value of the displayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }

        /**
         * Gets the value of the facetId property.
         * 
         */
        public String getFacetId() {
            return facetId;
        }

        /**
         * Sets the value of the facetId property.
         * 
         */
        public void setFacetId(String value) {
            this.facetId = value;
        }

        /**
         * Gets the value of the sortType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSortType() {
            return sortType;
        }

        /**
         * Sets the value of the sortType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSortType(String value) {
            this.sortType = value;
        }

        /**
         * Gets the value of the minValue property.
         * 
         */
        public long getMinValue() {
            return minValue;
        }

        /**
         * Sets the value of the minValue property.
         * 
         */
        public void setMinValue(long value) {
            this.minValue = value;
        }

        /**
         * Gets the value of the maxValue property.
         * 
         */
        public long getMaxValue() {
            return maxValue;
        }

        /**
         * Sets the value of the maxValue property.
         * 
         */
        public void setMaxValue(long value) {
            this.maxValue = value;
        }

        /**
         * Gets the value of the facetDisplay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFacetDisplay() {
            return facetDisplay;
        }

        /**
         * Sets the value of the facetDisplay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFacetDisplay(String value) {
            this.facetDisplay = value;
        }

        /**
         * Gets the value of the attributeId property.
         * 
         */
        public String getAttributeId() {
            return attributeId;
        }

        /**
         * Sets the value of the attributeId property.
         * 
         */
        public void setAttributeId(String value) {
            this.attributeId = value;
        }

        /**
         * Gets the value of the attributeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttributeName() {
            return attributeName;
        }

        /**
         * Sets the value of the attributeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttributeName(String value) {
            this.attributeName = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartDate(String value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndDate(String value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the displayMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayMode() {
            return displayMode;
        }

        /**
         * Sets the value of the displayMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayMode(String value) {
            this.displayMode = value;
        }

        /**
         * Gets the value of the glossaryItem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGlossaryItem() {
            return glossaryItem;
        }

        /**
         * Sets the value of the glossaryItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGlossaryItem(String value) {
            this.glossaryItem = value;
        }

        /**
         * Gets the value of the displayFacetRemoveLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayFacetRemoveLink() {
            return displayFacetRemoveLink;
        }

        /**
         * Sets the value of the displayFacetRemoveLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayFacetRemoveLink(String value) {
            this.displayFacetRemoveLink = value;
        }

        /**
         * Gets the value of the displayMobileFacet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayMobileFacet() {
            return displayMobileFacet;
        }

        /**
         * Sets the value of the displayMobileFacet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayMobileFacet(String value) {
            this.displayMobileFacet = value;
        }

        /**
         * Gets the value of the displayMobileFacetRemoveLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayMobileFacetRemoveLink() {
            return displayMobileFacetRemoveLink;
        }

        /**
         * Sets the value of the displayMobileFacetRemoveLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayMobileFacetRemoveLink(String value) {
            this.displayMobileFacetRemoveLink = value;
        }

        /**
         * Gets the value of the displayRecurrence property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayRecurrence() {
            return displayRecurrence;
        }

        /**
         * Sets the value of the displayRecurrence property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayRecurrence(String value) {
            this.displayRecurrence = value;
        }

        /**
         * Gets the value of the categoryWrapper property.
         * 
         * @return
         *     possible object is
         *     {@link Facets.Facet.CategoryWrapper }
         *     
         */
        public List<Facets.Facet.CategoryWrapper> getCategoryWrapper() {
            return categoryWrapper;
        }

        /**
         * Sets the value of the categoryWrapper property.
         * 
         * @param value
         *     allowed object is
         *     {@link Facets.Facet.CategoryWrapper }
         *     
         */
        public void setCategoryWrapper(List<Facets.Facet.CategoryWrapper> value) {
            this.categoryWrapper = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="applySubCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="displayDepFacet" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="displayContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="categoryPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "applySubCategory",
            "displayDepFacet",
            "displayContext",
            "categoryId",
            "categoryPath"
        })
        public static class CategoryWrapper {

            @XmlElement(required = true)
            protected String applySubCategory;
            @XmlElement(required = true)
            protected String displayDepFacet;
            @XmlElement(required = true)
            protected String displayContext;
            @XmlElement(required = true)
            protected String categoryId;
            @XmlElement(required = true)
            protected String categoryPath;

            /**
             * Gets the value of the applySubCategory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApplySubCategory() {
                return applySubCategory;
            }

            /**
             * Sets the value of the applySubCategory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApplySubCategory(String value) {
                this.applySubCategory = value;
            }

            /**
             * Gets the value of the displayDepFacet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayDepFacet() {
                return displayDepFacet;
            }

            /**
             * Sets the value of the displayDepFacet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayDepFacet(String value) {
                this.displayDepFacet = value;
            }

            /**
             * Gets the value of the displayContext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayContext() {
                return displayContext;
            }

            /**
             * Sets the value of the displayContext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayContext(String value) {
                this.displayContext = value;
            }

            /**
             * Gets the value of the categoryId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategoryId() {
                return categoryId;
            }

            /**
             * Sets the value of the categoryId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategoryId(String value) {
                this.categoryId = value;
            }

            /**
             * Gets the value of the categoryPath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategoryPath() {
                return categoryPath;
            }

            /**
             * Sets the value of the categoryPath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategoryPath(String value) {
                this.categoryPath = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="attributeValueId" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="attributeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="attrValuedisplay" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attributeValueId",
            "attributeValue",
            "attrValuedisplay",
            "sortOrder"
        })
        public static class ExcludeList {

            protected String attributeValueId;
            @XmlElement(required = true)
            protected String attributeValue;
            @XmlElement(required = true)
            protected String attrValuedisplay;
            @XmlElement(required = true)
            protected String sortOrder;

            /**
             * Gets the value of the attributeValueId property.
             * 
             */
            public String getAttributeValueId() {
                return attributeValueId;
            }

            /**
             * Sets the value of the attributeValueId property.
             * 
             */
            public void setAttributeValueId(String value) {
                this.attributeValueId = value;
            }

            /**
             * Gets the value of the attributeValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAttributeValue() {
                return attributeValue;
            }

            /**
             * Sets the value of the attributeValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAttributeValue(String value) {
                this.attributeValue = value;
            }

            /**
             * Gets the value of the attrValuedisplay property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAttrValuedisplay() {
                return attrValuedisplay;
            }

            /**
             * Sets the value of the attrValuedisplay property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAttrValuedisplay(String value) {
                this.attrValuedisplay = value;
            }

            /**
             * Gets the value of the sortOrder property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSortOrder() {
                return sortOrder;
            }

            /**
             * Sets the value of the sortOrder property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSortOrder(String value) {
                this.sortOrder = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="attributeValueId" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="attributeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="attrValuedisplay" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attributeValueId",
            "attributeValue",
            "sortOrder",
            "attrValuedisplay"
        })
        public static class PromoteList {

            protected String attributeValueId;
            @XmlElement(required = true)
            protected String attributeValue;
            protected String sortOrder;
            protected String attrValuedisplay;

            /**
             * Gets the value of the attributeValueId property.
             * 
             */
            public String getAttributeValueId() {
                return attributeValueId;
            }

            /**
             * Sets the value of the attributeValueId property.
             * 
             */
            public void setAttributeValueId(String value) {
                this.attributeValueId = value;
            }

            /**
             * Gets the value of the attributeValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAttributeValue() {
                return attributeValue;
            }

            /**
             * Sets the value of the attributeValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAttributeValue(String value) {
                this.attributeValue = value;
            }

            /**
             * Gets the value of the sortOrder property.
             * 
             */
            public String getSortOrder() {
                return sortOrder;
            }

            /**
             * Sets the value of the sortOrder property.
             * 
             */
            public void setSortOrder(String value) {
                this.sortOrder = value;
            }

            /**
             * Gets the value of the attrValuedisplay property.
             * 
             */
            public String getAttrValuedisplay() {
                return attrValuedisplay;
            }

            /**
             * Sets the value of the attrValuedisplay property.
             * 
             */
            public void setAttrValuedisplay(String value) {
                this.attrValuedisplay = value;
            }

        }

    }

}
