//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.04 at 05:01:06 PM GMT+05:30 
//


package com.bestbuy.searchplatform.integrationtests.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="keywordredirect" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="redirectTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="redirectUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="redirectType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="searchProfileId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

/**
 * Class to declare the variables used to create KeywordsRedirects
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "keywordredirect"
})
@XmlRootElement(name = "keywordredirects")
public class Keywordredirects {

    protected List<Keywordredirects.Keywordredirect> keywordredirect;

    /**
     * Gets the value of the keywordredirect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywordredirect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywordredirect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Keywordredirects.Keywordredirect }
     * 
     * 
     */
    public List<Keywordredirects.Keywordredirect> getKeywordredirect() {
        if (keywordredirect == null) {
            keywordredirect = new ArrayList<Keywordredirects.Keywordredirect>();
        }
        return this.keywordredirect;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="redirectTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="redirectUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="redirectType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="searchProfileId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "redirectTerm",
        "redirectUrl",
        "redirectType",
        "searchProfileId",
        "startDate",
        "endDate"
    })
    public static class Keywordredirect {

        @XmlElement(required = true)
        protected String redirectTerm;
        @XmlElement(required = true)
        protected String redirectUrl;
        @XmlElement(required = true)
        protected String redirectType;
        @XmlElement(required = true)
        protected String searchProfileId;
        @XmlElement(required = true)
        protected String startDate;
        @XmlElement(required = true)
        protected String endDate;

        /**
         * Gets the value of the redirectTerm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRedirectTerm() {
            return redirectTerm;
        }

        /**
         * Sets the value of the redirectTerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRedirectTerm(String value) {
            this.redirectTerm = value;
        }

        /**
         * Gets the value of the redirectUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRedirectUrl() {
            return redirectUrl;
        }

        /**
         * Sets the value of the redirectUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRedirectUrl(String value) {
            this.redirectUrl = value;
        }

        /**
         * Gets the value of the redirectType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRedirectType() {
            return redirectType;
        }

        /**
         * Sets the value of the redirectType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRedirectType(String value) {
            this.redirectType = value;
        }

        /**
         * Gets the value of the searchProfileId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchProfileId() {
            return searchProfileId;
        }

        /**
         * Sets the value of the searchProfileId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchProfileId(String value) {
            this.searchProfileId = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartDate(String value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndDate(String value) {
            this.endDate = value;
        }

    }

}
