//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.09 at 09:32:14 AM IST 
//


package com.bestbuy.search.bt.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="banner" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="banners_Banner_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Priority" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="banners_Context_Searchprofile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Context_KeyWord" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Start_Date_Month" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Start_Date_Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="Start_Date_Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="Start_Date_Hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="Start_Date_Minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="End_Date_Month" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="End_Date_Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="End_Date_Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="End_Date_Hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="End_Date_Minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="banners_Template" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Temp_Header1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Temp_Header2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Temp_Header3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Temp_AddTerm1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Temp_AddTerm2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Temp_AddTerm3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="banners_Theme_AssetID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "banner"
})
@XmlRootElement(name = "banners")
public class Banners {

    protected List<Banners.Banner> banner;

    /**
     * Gets the value of the banner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the banner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBanner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Banners.Banner }
     * 
     * 
     */
    public List<Banners.Banner> getBanner() {
        if (banner == null) {
            banner = new ArrayList<Banners.Banner>();
        }
        return this.banner;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="banners_Banner_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Priority" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="banners_Context_Searchprofile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Context_KeyWord" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Start_Date_Month" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Start_Date_Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Start_Date_Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="Start_Date_Hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Start_Date_Minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="End_Date_Month" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="End_Date_Day" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="End_Date_Year" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="End_Date_Hour" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="End_Date_Minute" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="banners_Template" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Temp_Header1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Temp_Header2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Temp_Header3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Temp_AddTerm1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Temp_AddTerm2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Temp_AddTerm3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="banners_Theme_AssetID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bannersBannerName",
        "bannersPriority",
        "bannersContextSearchprofile",
        "bannersContextKeyWord",
        "startDateMonth",
        "startDateDay",
        "startDateYear",
        "startDateHour",
        "startDateMinute",
        "endDateMonth",
        "endDateDay",
        "endDateYear",
        "endDateHour",
        "endDateMinute",
        "bannersTemplate",
        "bannersTempHeader1",
        "bannersTempHeader2",
        "bannersTempHeader3",
        "bannersTempAddTerm1",
        "bannersTempAddTerm2",
        "bannersTempAddTerm3",
        "bannersThemeAssetID"
    })
    public static class Banner {

        @XmlElement(name = "banners_Banner_Name", required = true)
        protected String bannersBannerName;
        @XmlElement(name = "banners_Priority")
        protected String bannersPriority;
        @XmlElement(name = "banners_Context_Searchprofile", required = true)
        protected String bannersContextSearchprofile;
        @XmlElement(name = "banners_Context_KeyWord", required = true)
        protected String bannersContextKeyWord;
        @XmlElement(name = "Start_Date_Month", required = true)
        protected String startDateMonth;
        @XmlElement(name = "Start_Date_Day")
        protected String startDateDay;
        @XmlElement(name = "Start_Date_Year")
        protected String startDateYear;
        @XmlElement(name = "Start_Date_Hour")
        protected String startDateHour;
        @XmlElement(name = "Start_Date_Minute")
        protected String startDateMinute;
        @XmlElement(name = "End_Date_Month", required = true)
        protected String endDateMonth;
        @XmlElement(name = "End_Date_Day")
        protected String endDateDay;
        @XmlElement(name = "End_Date_Year")
        protected String endDateYear;
        @XmlElement(name = "End_Date_Hour")
        protected String endDateHour;
        @XmlElement(name = "End_Date_Minute")
        protected String endDateMinute;
        @XmlElement(name = "banners_Template", required = true)
        protected String bannersTemplate;
        @XmlElement(name = "banners_Temp_Header1", required = true)
        protected String bannersTempHeader1;
        @XmlElement(name = "banners_Temp_Header2", required = true)
        protected String bannersTempHeader2;
        @XmlElement(name = "banners_Temp_Header3", required = true)
        protected String bannersTempHeader3;
        @XmlElement(name = "banners_Temp_AddTerm1", required = true)
        protected String bannersTempAddTerm1;
        @XmlElement(name = "banners_Temp_AddTerm2", required = true)
        protected String bannersTempAddTerm2;
        @XmlElement(name = "banners_Temp_AddTerm3", required = true)
        protected String bannersTempAddTerm3;
        @XmlElement(name = "banners_Theme_AssetID")
        protected String bannersThemeAssetID;

        /**
         * Gets the value of the bannersBannerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersBannerName() {
            return bannersBannerName;
        }

        /**
         * Sets the value of the bannersBannerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersBannerName(String value) {
            this.bannersBannerName = value;
        }

        /**
         * Gets the value of the bannersPriority property.
         * 
         */
        public String getBannersPriority() {
            return bannersPriority;
        }

        /**
         * Sets the value of the bannersPriority property.
         * 
         */
        public void setBannersPriority(String value) {
            this.bannersPriority = value;
        }

        /**
         * Gets the value of the bannersContextSearchprofile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersContextSearchprofile() {
            return bannersContextSearchprofile;
        }

        /**
         * Sets the value of the bannersContextSearchprofile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersContextSearchprofile(String value) {
            this.bannersContextSearchprofile = value;
        }

        /**
         * Gets the value of the bannersContextKeyWord property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersContextKeyWord() {
            return bannersContextKeyWord;
        }

        /**
         * Sets the value of the bannersContextKeyWord property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersContextKeyWord(String value) {
            this.bannersContextKeyWord = value;
        }

        /**
         * Gets the value of the startDateMonth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartDateMonth() {
            return startDateMonth;
        }

        /**
         * Sets the value of the startDateMonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartDateMonth(String value) {
            this.startDateMonth = value;
        }

        /**
         * Gets the value of the startDateDay property.
         * 
         */
        public String getStartDateDay() {
            return startDateDay;
        }

        /**
         * Sets the value of the startDateDay property.
         * 
         */
        public void setStartDateDay(String value) {
            this.startDateDay = value;
        }

        /**
         * Gets the value of the startDateYear property.
         * 
         */
        public String getStartDateYear() {
            return startDateYear;
        }

        /**
         * Sets the value of the startDateYear property.
         * 
         */
        public void setStartDateYear(String value) {
            this.startDateYear = value;
        }

        /**
         * Gets the value of the startDateHour property.
         * 
         */
        public String getStartDateHour() {
            return startDateHour;
        }

        /**
         * Sets the value of the startDateHour property.
         * 
         */
        public void setStartDateHour(String value) {
            this.startDateHour = value;
        }

        /**
         * Gets the value of the startDateMinute property.
         * 
         */
        public String getStartDateMinute() {
            return startDateMinute;
        }

        /**
         * Sets the value of the startDateMinute property.
         * 
         */
        public void setStartDateMinute(String value) {
            this.startDateMinute = value;
        }

        /**
         * Gets the value of the endDateMonth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndDateMonth() {
            return endDateMonth;
        }

        /**
         * Sets the value of the endDateMonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndDateMonth(String value) {
            this.endDateMonth = value;
        }

        /**
         * Gets the value of the endDateDay property.
         * 
         */
        public String getEndDateDay() {
            return endDateDay;
        }

        /**
         * Sets the value of the endDateDay property.
         * 
         */
        public void setEndDateDay(String value) {
            this.endDateDay = value;
        }

        /**
         * Gets the value of the endDateYear property.
         * 
         */
        public String getEndDateYear() {
            return endDateYear;
        }

        /**
         * Sets the value of the endDateYear property.
         * 
         */
        public void setEndDateYear(String value) {
            this.endDateYear = value;
        }

        /**
         * Gets the value of the endDateHour property.
         * 
         */
        public String getEndDateHour() {
            return endDateHour;
        }

        /**
         * Sets the value of the endDateHour property.
         * 
         */
        public void setEndDateHour(String value) {
            this.endDateHour = value;
        }

        /**
         * Gets the value of the endDateMinute property.
         * 
         */
        public String getEndDateMinute() {
            return endDateMinute;
        }

        /**
         * Sets the value of the endDateMinute property.
         * 
         */
        public void setEndDateMinute(String value) {
            this.endDateMinute = value;
        }

        /**
         * Gets the value of the bannersTemplate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersTemplate() {
            return bannersTemplate;
        }

        /**
         * Sets the value of the bannersTemplate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersTemplate(String value) {
            this.bannersTemplate = value;
        }

        /**
         * Gets the value of the bannersTempHeader1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersTempHeader1() {
            return bannersTempHeader1;
        }

        /**
         * Sets the value of the bannersTempHeader1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersTempHeader1(String value) {
            this.bannersTempHeader1 = value;
        }

        /**
         * Gets the value of the bannersTempHeader2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersTempHeader2() {
            return bannersTempHeader2;
        }

        /**
         * Sets the value of the bannersTempHeader2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersTempHeader2(String value) {
            this.bannersTempHeader2 = value;
        }

        /**
         * Gets the value of the bannersTempHeader3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersTempHeader3() {
            return bannersTempHeader3;
        }

        /**
         * Sets the value of the bannersTempHeader3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersTempHeader3(String value) {
            this.bannersTempHeader3 = value;
        }

        /**
         * Gets the value of the bannersTempAddTerm1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersTempAddTerm1() {
            return bannersTempAddTerm1;
        }

        /**
         * Sets the value of the bannersTempAddTerm1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersTempAddTerm1(String value) {
            this.bannersTempAddTerm1 = value;
        }

        /**
         * Gets the value of the bannersTempAddTerm2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersTempAddTerm2() {
            return bannersTempAddTerm2;
        }

        /**
         * Sets the value of the bannersTempAddTerm2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersTempAddTerm2(String value) {
            this.bannersTempAddTerm2 = value;
        }

        /**
         * Gets the value of the bannersTempAddTerm3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBannersTempAddTerm3() {
            return bannersTempAddTerm3;
        }

        /**
         * Sets the value of the bannersTempAddTerm3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBannersTempAddTerm3(String value) {
            this.bannersTempAddTerm3 = value;
        }

        /**
         * Gets the value of the bannersThemeAssetID property.
         * 
         */
        public String getBannersThemeAssetID() {
            return bannersThemeAssetID;
        }

        /**
         * Sets the value of the bannersThemeAssetID property.
         * 
         */
        public void setBannersThemeAssetID(String value) {
            this.bannersThemeAssetID = value;
        }

    }

}
